baseURL = "/"
publishdir = "public"
theme = "absent"

title = "wooly mammoth's mighty absence"

languageCode = "en-US"

# allow fenced code blocks, instead of `{{< highlight ... >}}` shortcodes,
# which are unwieldly and less fun than using pure Markdown syntax
pygmentsCodeFences = true
# allow us to hook in custom CSS to render the site's styles
pygmentsUseClasses = true

# get information about the Git repo, such as last commit to a file
# enableGitInfo = true

canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true
paginate = "5"

[params]
author = "marshall"
image = "/images/me.png"
mainSections = "posts"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
expiryDate = ["expiryDate"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[permalinks]
# mf2 = "/mf2/:slug/"
posts = "/posts/:slug/"
tags = "/tags/:title/"

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
isPlainText = true
mediatype = "application/rss"
notAlternative = true

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 3
[markup.goldmark]
[markup.goldmark.extensions]
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = false
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "now"
name = "/now"
title = "/now"
url = "/now/"
weight = 1
[[menu.main]]
identifier = "monthly-lists"
name = "last month's stuff"
title = "monthly-lists"
url = "/monthly-lists/"
weight = 2
[[menu.main]]
identifier = "rss"
name = "rss"
title = "rss"
url = "/feed.xml"
weight = 3
