baseURL: /
publishdir: public
theme: absent
title: wooly mammoth's mighty absence
languageCode: en-US

pygmentsCodeFences: true
# hook in custom CSS to render site styles
pygmentsUseClasses: true
canonifyURLs: true
enableEmoji: true
enableRobotsTXT: true
paginate: 5
# get info about the Git repo
# enableGitInfo: true

params:
  author: "marshall"
  image: /images/me.png
  mainSections: posts
  # h-card info. for more, see: microformats.org/wiki/h-card#Properties
  hCardName: "marshall"
  hCardJobTitle: "freelancer"
  hCardLocality: "colorado springs"
  hCardRegion: "colorado"
  # pronouns info: https://www.jvt.me/posts/2019/04/10/pronouns-microformats/
  hCardNominativePronoun: "he"
  hCardObliquePronoun: "him"
  hCardPossessivePronoun: "his"
  hCardGithub: "absentmammoth"
  hCardInstagram: "absentmammoth"
  hCardLastFM: "absentmammoth"
  hCardTumblr: "moretherapy"
  hCardTwitter: "absntmammoth"
  hCardEmail: ""

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  expiryDate:
    - expiryDate
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

permalinks:
  posts: /posts/:slug/
  tags: /tags/:title/

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
    - RSS

outputFormats:
  RSS:
    baseName: feed
    isPlainText: true
    mediatype: application/rss
    notAlternative: true

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 3
  goldmark:
    extensions:
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: dracula
    tabWidth: 4

menu:
  main:
    - identifier: now
      name: /now
      title: /now
      url: /now/
      weight: 1
    - identifier: monthly-lists
      name: last month's stuff
      title: monthly-lists
      url: /monthly-lists/
      weight: 2
    - identifier: rss
      name: rss
      title: rss
      url: /feed.xml
      weight: 3
